# Information
site_name: OAlienO's Blog

# Repository
repo_name: 'OAlienO/OAlienO'
repo_url: 'https://github.com/OAlienO/OAlienO.github.io'

# Content
pages:
    - HOME: index.md
    - MATH:
      - README: math/README.md
      - 數學名詞: math/math-term.md
      - 數論:
        - 模運算: math/number-theory/modular.md
        - 費馬小定理: math/number-theory/fermat.md
        - 二次剩餘: math/number-theory/quadratic-residue.md
        - 連分數: math/number-theory/continued-fractions.md
        - 中國剩餘定理: math/number-theory/chinese-remainder-theorem.md
        - 擴展歐基里得演算法: math/number-theory/exgcd.md
        - Legendre Symbol: math/number-theory/legendre.md
      - 群論:
        - 群論簡介: math/group-theory/introduction.md
    - CRYPTO:
      - README: crypto/README.md
      - 古典密碼: crypto/classical.md
      - 對稱式密碼:
        - DES: crypto/symmetric/des.md
        - AES: crypto/symmetric/aes.md
        - 工作模式: crypto/symmetric/mode.md
        - Padding Oracle Attack: crypto/symmetric/padding-oracle.md
      - 非對稱式密碼:
        - Diffie-Hellman:
          - Introduction to Diffie-Hellman: crypto/asymmetric/diffie-hellman/introduction.md
          - Backdoor in Diffie-Hellman: crypto/asymmetric/diffie-hellman/backdoor.md
        - RSA:
          - Introduction to RSA: crypto/asymmetric/rsa/introduction.md
          - Pollard's p-1 Algorithm: crypto/asymmetric/rsa/pollard.md
          - Williams's p+1 Algorithm: crypto/asymmetric/rsa/williams.md
          - Fermat's Factorization Method: crypto/asymmetric/rsa/fermat.md
          - Wiener's Attack: crypto/asymmetric/rsa/wiener.md
          - Common Factor Attack: crypto/asymmetric/rsa/common-factor-attack.md
          - Common Modulus Attack: crypto/asymmetric/rsa/common-modulus-attack.md
          - Coppersmith Attack: crypto/asymmetric/rsa/coppersmith.md
          - Backdoor in RSA: crypto/asymmetric/rsa/backdoor.md
          - 實做: crypto/asymmetric/rsa/implementation.md
        - Rabin: crypto/asymmetric/rabin.md
      - 哈希函數:
        - Merkle–Damgård Construction: crypto/hash/merkle-damgard.md
        - Birthday Attack: crypto/hash/birthday-attack.md
        - Rainbow Table: crypto/hash/rainbow-table.md
        - Length Extension Attack: crypto/hash/length-extension-attack.md
        - 實做: crypto/hash/implementation.md
      - 經典攻擊:
        - BEAST Attack: crypto/classic/beast.md
        - POODLE Attack: crypto/classic/poodle.md

# Theme
theme: 'material'

# Customization
extra_javascript: 
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Extensions
markdown_extensions:
    - pymdownx.arithmatex
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tilde
