# Information
site_name: OAlienO's Blog

# Repository
repo_name: 'OAlienO/OAlienO'
repo_url: 'https://github.com/OAlienO/OAlienO.github.io'

# Content
pages:
    - HOME: index.md
    - MATH:
      - 相關資源: math/resources.md
      - 數學名詞: math/math-term.md
      - 數論:
        - 連分數: math/number-theory/continued-fractions.md
        - 模運算: math/number-theory/modular.md
        - 費馬小定理: math/number-theory/fermat.md
        - 二次剩餘: math/number-theory/quadratic-residue.md
        - 中國剩餘定理: math/number-theory/chinese-remainder-theorem.md
        - 擴展歐基里得演算法: math/number-theory/exgcd.md
        - Euler's Totient Function: math/number-theory/euler-totient.md
        - Carmichael Function: math/number-theory/carmichael-function.md
        - Legendre Symbol: math/number-theory/legendre.md
        - Resultant: math/number-theory/resultant.md
      - 群論: math/group-theory.md
      - Lattice:
        - 定義: math/lattice/definition.md
    - CRYPTO:
      - 相關資源: crypto/resources.md
      - 古典密碼: crypto/classical.md
      - 對稱式密碼:
        - DES: crypto/symmetric/des.md
        - AES: crypto/symmetric/aes.md
        - Block Cipher Modes: crypto/symmetric/mode.md
        - Padding Oracle Attack: crypto/symmetric/padding-oracle.md
      - 非對稱式密碼:
        - Diffie-Hellman:
          - Introduction to Diffie-Hellman: crypto/asymmetric/diffie-hellman/introduction.md
          - ElGamal: crypto/asymmetric/diffie-hellman/elgamal.md
          - Big-Step Giant-Step: crypto/asymmetric/diffie-hellman/baby-step-giant-step.md
          - Pollard's Rho Algorithm: crypto/asymmetric/diffie-hellman/pollard-rho.md
          - Pohlig Hellman Algorithm: crypto/asymmetric/diffie-hellman/pohlig-hellman.md
          - Backdoor in Diffie-Hellman: crypto/asymmetric/diffie-hellman/backdoor.md
        - RSA:
          - Introduction to RSA: crypto/asymmetric/rsa/introduction.md
          - factor n with d: crypto/asymmetric/rsa/factor-n-with-d.md
          - Pollard's p-1 Algorithm: crypto/asymmetric/rsa/pollard.md
          - Williams's p+1 Algorithm: crypto/asymmetric/rsa/williams.md
          - Fermat's Factorization Method: crypto/asymmetric/rsa/fermat.md
          - Wiener's Attack: crypto/asymmetric/rsa/wiener.md
          - Common Factor Attack: crypto/asymmetric/rsa/common-factor-attack.md
          - Common Modulus Attack: crypto/asymmetric/rsa/common-modulus-attack.md
          - Coppersmith Attack: crypto/asymmetric/rsa/coppersmith.md
          - Backdoor in RSA: crypto/asymmetric/rsa/backdoor.md
          - 實做: crypto/asymmetric/rsa/implementation.md
        - Rabin: crypto/asymmetric/rabin.md
        - Elliptic Curve:
          - Introduction to Elliptic Curve: crypto/asymmetric/elliptic-curve/introduction.md
          - Elliptic Curve Key Exchange: crypto/asymmetric/elliptic-curve/key-exchange.md
      - 哈希函數:
        - Merkle–Damgård Construction: crypto/hash/merkle-damgard.md
        - Birthday Attack: crypto/hash/birthday-attack.md
        - Rainbow Table: crypto/hash/rainbow-table.md
        - Length Extension Attack: crypto/hash/length-extension-attack.md
        - 實做: crypto/hash/implementation.md
      - Digital Signature:
        - DSA: crypto/digital-signature/dsa.md
        - DSA Known Partial Nonce Attack: crypto/digital-signature/dsa-known-partial-nonce.md
        - ECDSA: crypto/digital-signature/ecdsa.md
      - 經典攻擊:
        - BEAST Attack: crypto/classic/beast.md
        - POODLE Attack: crypto/classic/poodle.md
        - Dual EC DRBG Backdoor: crypto/classic/dual-ec.md
    - PWN:
      - 常用指令與工具: pwn/tools.md
      - 保護機制: pwn/protection.md
      - gdb tips: pwn/gdb-tips.md
      - Format String: pwn/format-string.md
      - return to libc: pwn/return-to-libc.md
      - return to dl-resolve: pwn/return-to-dl-resolve.md
      - Heap Exploitation:
        - House of Force: pwn/heap/house-of-force.md
        - House of Orange: pwn/heap/house-of-orange.md
    - WEB:
      - Information Gathering: web/information-gathering.md
      - SQL injection: web/sql-injection.md
      - XSS: web/xss.md
      - Tricks in PHP: web/php.md
      - DDOS: web/ddos.md
    - ALGORITHM:
      - 相關資源: algorithm/resources.md
      - Floyd's Cycle-Finding Algorithm: algorithm/floyd-cycle-finding.md
    - MOVIES & SERIES:
      - 列表: movies-series/list.md
    - OTHERS:
      - QEMU Internals: others/qemu-internals.md
      - x86 Instructions Format: others/x86-instructions-format.md

# Theme
theme:
    name: 'material'
    palette:
        primary: 'teal'
    feature:
        tabs: true

# Customization
extra_javascript: 
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

# Extensions
markdown_extensions:
    - pymdownx.arithmatex
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tilde
